export const refs = {
	lobbyScreen: document.getElementById("lobbyScreen"),
	gameScreen: document.getElementById("gameScreen"),
	highscoreScreen: document.getElementById("highscoreScreen"),
	createLobbyForm: document.getElementById("createLobbyForm"),
	usernameInput: document.getElementById("usernameInput"),
	joinLobbyForm: document.getElementById("joinLobbyForm"),
	joinCodeInput: document.getElementById("joinCodeInput"),
	lobbyStatus: document.getElementById("lobbyStatus"),
	openHighscoresFromLobby: document.getElementById("openHighscoresFromLobby"),
	gameLobbyCode: document.getElementById("gameLobbyCode"),
	gameStatus: document.getElementById("gameStatus"),
	roundTimeline: document.getElementById("roundTimeline"),
	gameTargetNumber: document.getElementById("gameTargetNumber"),
	scoreboardList: document.getElementById("scoreboardList"),
	optionList: document.getElementById("optionList"),
	leaveLobbyButton: document.getElementById("leaveLobbyButton"),
	openHighscoresFromGame: document.getElementById("openHighscoresFromGame"),
	highscoreStatus: document.getElementById("highscoreStatus"),
	highscoreList: document.getElementById("highscoreList"),
	backToLobbyButton: document.getElementById("backToLobbyButton"),
};
